FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY shared/ shared/
COPY patient_service/ patient_service/
CMD ["uvicorn", "patient_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
